"""Fix model imports for available tests

Revision ID: 412ed442ef4d
Revises: 57fab51d734a
Create Date: 2026-09-14 15:31:29.715178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '412ed442ef4d'
down_revision: Union[str, Sequence[str], None] = '57fab51d734a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('available_tests', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('available_tests', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
