"""add discount fields to invoices

Revision ID: 48c86452daa0
Revises: 98da338f8576
Create Date: 2026-10-03 16:22:05.682687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48c86452daa0'
down_revision: Union[str, Sequence[str], None] = '98da338f8576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'discount_amount')
    op.drop_column('invoices', 'discount_percentage')
    # ### end Alembic commands ###
