"""Fix model imports for available tests

Revision ID: 57fab51d734a
Revises: 
Create Date: 2026-09-14 15:26:49.913679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57fab51d734a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('available_tests', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_available_tests_test_type'), 'available_tests', ['test_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_available_tests_test_type'), table_name='available_tests')
    op.alter_column('available_tests', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
